-- Script SQL pour créer la table REQUETE
-- Base de données : PIERRE

CREATE TABLE IF NOT EXISTS REQUETE (
    ID_REQUETE INT AUTO_INCREMENT PRIMARY KEY,
    PRENOM VARCHAR(50) NOT NULL,
    NOM VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEPHONE VARCHAR(20),
    LOGICIEL VARCHAR(100) NOT NULL,
    OS VARCHAR(50) NOT NULL,
    PROBLEME TEXT NOT NULL,
    DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index pour améliorer les performances de recherche
CREATE INDEX idx_email ON REQUETE(EMAIL);
CREATE INDEX idx_date ON REQUETE(DATE_CREATION);
